
project_id = "rorweifvcparnpgztvsq"

[api]
enabled = true
cors = {
  enabled = true,
  allowed_methods = ["GET", "POST", "PUT", "DELETE", "OPTIONS"],
  allowed_headers = ["authorization", "x-client-info", "apikey", "content-type", "accept", "accept-encoding", "x-requested-with"],
  max_age = 86400
}

[functions]
[functions.send-whatsapp]
verify_jwt = true

[functions.generate-embedding]
verify_jwt = true

[functions.generate-file-embedding]
verify_jwt = true

[functions.messenger-webhook]
verify_jwt = false

[functions.whatsapp-webhook]
verify_jwt = false
