
# This file is used to configure your Supabase project.
# For more information, please visit: https://supabase.com/docs/guides/getting-started/local-development

[api]
port = 54321
schemas = ["public", "storage", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322

[studio]
port = 54323

[inbucket]
port = 54324
smtp_port = 54325
pop3_port = 54326

[auth]
site_url = "http://localhost:3000"
additional_redirect_urls = ["https://localhost:3000"]
jwt_expiry = 3600
enable_signup = true

[storage]

[realtime]
postgres_changes.channel_defaults = ["*"]
enable = true

[edge_functions]
[edge_functions.generate-embedding]
verify_jwt = true
[edge_functions.generate-file-embedding]
verify_jwt = true
[edge_functions.messenger-webhook]
verify_jwt = true
[edge_functions.send-whatsapp]
verify_jwt = true
[edge_functions.whatsapp-webhook]
verify_jwt = false
