project_id = "txxfaccdpvoacifuumya"
[functions.send-whatsapp]
verify_jwt = false
[functions.whatsapp-webhook]
verify_jwt = false
[functions.generate-embedding]
verify_jwt = false
[functions.generate-file-embedding]
verify_jwt = false